### ISSUE TITLE
Handling performance issues

### ISSUE THREAD

**Issue by JohanRonstrom** [garethjmsaunders/trello-coloured-lists#3]
Hi! Thanks for the script!

On big Trello boards, I get a significant performance hit with the script running on body hover.

I have changed the script locally to instead run once 5 seconds after document ready, and then again once every 5 minutes. That has turned out to be more than enough for me.

Like so:
```
    function changeColors() {
        console.log('GJMS: Changing column colours...');
        // ...
    }
    setTimeout(changeColors, 5000);
    setInterval(changeColors, 300000);
```

Regards,
Johan

**Comment by garethjmsaunders** [comment]
Thanks Johan, that's a really helpful enhancement. I'll amend my code asap. I've often thought about adapting how often it runs, this is a useful update.

**Comment by garethjmsaunders** [comment]
I've just updated the script (v5.0.0). 

Many thanks @JohanRonstrom for the improvement.
