### ISSUE TITLE
Test has prio over bugs

### ISSUE THREAD

**Issue by JohanRonstrom** [garethjmsaunders/trello-coloured-lists#4]
I noticed that because the definition of Yellow is after the definition of Red, columns with names such as "Issues from test session" or "Bugs reported by QA" is colored yellow instead of red. I changed the order locally to "Yellow, Orange, Red" instead of "Red, Orange, Yellow". Unless there are examples where this is not wanted, you might want to consider changing that in the repo as well. :-)

**Comment by JohanRonstrom** [comment]
Or, if you want the column "Minor Bugs" to be orange... Then the order "Yellow, Red, Orange" might be more appropriate..

**Comment by garethjmsaunders** [comment]
Thanks @JohanRonstrom, I've never considered adding any kind of logic checking to make sure this sort of thing doesn't happen. I always just kept it as simple as possible and open to myself or others moving things around as required. My columns tend to be named with short titles, like "Bugs", "QA", "Inbox".

I've updated the code to make this clearer with a simple comment to say "Customise the keywords and the order of colours as you require."

One day I may turn this into a proper browser plugin/extension but until then I hope you can make do with customising it as you need.
